### PR TITLE
[#1907] improvement(trino-connector): Add missing `@Override` annotation in subclass method

### PR DESCRIPTION
**Pull request by caican00**
### What changes were proposed in this pull request?

Add missing `@Override` annotation in subclass method.

### Why are the changes needed?

Used to identify overridden parent class methods.

Fix: [#1907](https://github.com/datastrato/gravitino/issues/1907)

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

`./gradlew :trino-connector:test 
`

### CODE REVIEW

**Comment by caican00** [comment]
@justinmclean Could you please help review this PR? Thank you

**Comment by justinmclean** [comment]
createTable in MySQLMetadataAdapter.java has the same issue can you fix that as well?

**Comment by caican00** [comment]
> createTable in MySQLMetadataAdapter.java has the same issue can you fix that as well?

@justinmclean Hi, i have fixed the same issue in MySQLMetadataAdapter.java, and in addition, I also fixed the same problem in other classes, such as:
```
buildInternalConnectorConfig and getMetadataAdapter in HiveConnectorAdapter.java
buildInternalConnectorConfig and getMetadataAdapter in IcebergConnectorAdapter.java
buildInternalConnectorConfig and getMetadataAdapter in MySQLConnectorAdapter.java
buildInternalConnectorConfig and getMetadataAdapter in PostgreSQLConnectorAdapter.java
```

**Comment by yuqi1129** [comment]
Is it ready for review? @caican00

**Comment by justinmclean** [comment]
It looks ready to me.

**Comment by caican00** [comment]
> ./gradlew :trino-connector:test

@yuqi1129  yes, I have successfully executed `./gradlew :trino-connector:test`

**Comment by caican00** [comment]
> Is it ready for review? @caican00

@yuqi1129  yes, I have successfully executed `./gradlew :trino-connector:test`

**Review by yuqi1129 — APPROVED** [review]
LGTM, thanks @caican00 for your work.

**Pull request merged**
