### PR TITLE
[#1953] [#1946] [#1941] [#1920] [#1910] improment(trino): make version atomic to keep thread safe

### LINKED ISSUE #1953: [Improvement] Possible thread issue in `PostgreSQLConnectorAdapter.java`
### What would you like to be improved?

Static field version is being updated in non-static method buildInternalConnectorConfig.

Correctly updating a static field from a non-static method is tricky to get right and could easily lead to bugs if there are multiple class instances and/or multiple threads in play. Ideally, static fields are only updated from synchronized static methods.

### How should we improve?

Change method to static?

### PR DESCRIPTION
**Pull request by coolderli**
### What changes were proposed in this pull request?

close #1953 #1946 #1941 #1920 #1910 

### Why are the changes needed?

Fix: #1953 #1946 #1941 #1920 #1910 

### Does this PR introduce _any_ user-facing change?

- no

### How was this patch tested?

- ut

### CODE REVIEW

**Comment by justinmclean** [comment]
@jerryshao looks fine to me, what do you think?

**Comment by yuqi1129** [comment]
@diqiu50 
IMO, the version can be changed at the same time. What do you think?

**Comment by coolderli** [comment]
@jerryshao @yuqi1129 @diqiu50 Any further comment about this? Thanks.

**Comment by diqiu50** [comment]
> @diqiu50 IMO, the version can be changed at the same time. What do you think?

The version is used exclusively by the load catalog thread. Changing it to atomic would be better.

**Review by diqiu50 — APPROVED** [review]

**Comment by YxAc** [comment]
I noticed that #1946 #1941 #1920 #1910 have not been closed yet, can you deal with them when you are free? @justinmclean @diqiu50 @yuqi1129

**Pull request merged**
