### PR TITLE
[#2285] improvement(core): fix thread issue for BaseCatalog

### PR DESCRIPTION
**Pull request by YxAc**
### What changes were proposed in this pull request?
- fix thread issue for BaseCatalog

### Why are the changes needed?
Fix: #2285 

### Does this PR introduce _any_ user-facing change?
N/A

### How was this patch tested?
NO

### CODE REVIEW

**Review by justinmclean — APPROVED** [review]
Thanks for taking the time to fix this.

**Comment by yuqi1129** [comment]
@YxAc 
Given the fact that an object lock protects the properties, I wonder in which scenario it is thread-safe.

**Comment by YxAc** [comment]
> @YxAc Given the fact that an object lock protects the properties, I wonder in which scenario it is thread-safe.

```
if (properties == null) {
      synchronized (this) {
        if (properties == null) {
          Preconditions.checkArgument(entity != null, ENTITY_IS_NOT_SET);
          properties = Maps.newHashMap(entity.getProperties());   //  Mark
          properties
              .entrySet()
              .removeIf(
                  entry -> ops().catalogPropertiesMetadata().isHiddenProperty(entry.getKey()));
        }
      }
```
When threadA gets _the 'Mark' line_, threadB can skip the synchronized block because properties are no longer null, then threadB get an intermediate value with incomplete initialization.

**Comment by yuqi1129** [comment]
> > @YxAc Given the fact that an object lock protects the properties, I wonder in which scenario it is thread-safe.
> 
> ```
> if (properties == null) {
>       synchronized (this) {
>         if (properties == null) {
>           Preconditions.checkArgument(entity != null, ENTITY_IS_NOT_SET);
>           properties = Maps.newHashMap(entity.getProperties());   //  Mark
>           properties
>               .entrySet()
>               .removeIf(
>                   entry -> ops().catalogPropertiesMetadata().isHiddenProperty(entry.getKey()));
>         }
>       }
> ```
> 
> When threadA gets _the 'Mark' line_, threadB can skip the synchronized block because properties are no longer null, then threadB get an intermediate value with incomplete initialization.

I see.

**Pull request merged**
