### PR TITLE
 [#1640] Improvement : Standardise the invocation method for the Builder pattern 

### PR DESCRIPTION
**Pull request by hiirrxnn**
### What changes were proposed in this pull request?

Standardise the invocation method for the Builder pattern 

### Why are the changes needed?

Improvement

Fix: #1640

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by hiirrxnn** [comment]
Please review and tell if this method is correct.

**Comment by mchades** [comment]
> Please review and tell if this method is correct.

Totally correct! Just ensure the CI passed

**Comment by hiirrxnn** [comment]
Any advice on how I can do that ?

**Comment by mchades** [comment]
step1:
image

step2:
image

step3:
copy above command and run
`./gradlew :common:spotlessApply`

**Review by mchades — APPROVED** [review]
LGTM.

Thanks for your contribution!

**Comment by hiirrxnn** [comment]
Should I get started for the other files in this PR itself or another one?

**Comment by mchades** [comment]
> Should I get started for the other files in this PR itself or another one?

In another one, Thanks!

**Pull request merged**
