### PR TITLE
[#2164] improvement(jdbc-catalog): Replace mutable array with immutable array.

### PR DESCRIPTION
**Pull request by M-Faheem-Khan**
### What changes were proposed in this pull request?

Address the [MutablePublicArray](https://errorprone.info/bugpattern/MutablePublicArray) issue raised by Error Prone in `JdbcConnectorUtils.java` by replacing the Mutable Array with an immutable array and by creating the `getTableType` method which returns a string copy of the array.

### Why are the changes needed?

The mutable array is not a constant and can be modified by clients of this class. See [https://errorprone.info/bugpattern/MutablePublicArray](https://errorprone.info/bugpattern/MutablePublicArray)

Fix: # (2164)

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

Yes, all Integration Test and Build Test pass(ran locally, see [fork pr test](https://github.com/M-Faheem-Khan/gravitino/pull/3#issuecomment-1937410115)).

### CODE REVIEW

**Review by justinmclean — APPROVED** [review]
LGTM - Thanks for your contribution.

**Review by qqqttt123 — APPROVED** [review]
LGTM.

**Comment by yuqi1129** [comment]
@M-Faheem-Khan 
Thank you for your contributions.

**Comment by qqqttt123** [comment]
@M-Faheem-Khan Welcome to join the Gravitinio community! Enjoy your trip!

**Pull request merged**
