### PR TITLE
[#3028] fix incorrectly accessed static fields

### LINKED ISSUE #3028: [Improvement] Access of static fields in AuthorizationUtils.java
### What would you like to be improved?

1. Access of static fields should be via the class they exist in not via a subclass. Both GROUP_SCHEMA_NAME and SYSTEM_CATALOG_RESERVED_NAME are incorrectly accessed in AuthorizationUtils.java.

### How should we improve?

Use correct class when accesing GROUP_SCHEMA_NAME and SYSTEM_CATALOG_RESERVED_NAME.

### PR DESCRIPTION
**Pull request by hanwxx**
### What changes were proposed in this pull request?

(Please outline the changes and how this PR fixes the issue.)

### Why are the changes needed?
Fix: #3028

### Does this PR introduce _any_ user-facing change?
no
### How was this patch tested?
Use existing test cases in TestAuthorizationUtils.class

### CODE REVIEW

**Comment by hanwxx** [comment]
@yuqi1129 hello,can help review this

**Comment by mchades** [comment]
Could you please also fix the `SYSTEM_CATALOG_RESERVED_NAME` mentioned in the issue?

(BTW, Please modify the PR title and description according to the template format)

**Comment by hanwxx** [comment]
get,  I'll modify it

**Comment by hanwxx** [comment]
@mchades hello，please see again. thanks

**Review by mchades — APPROVED** [review]
LGTM

**Pull request merged**
