### PR TITLE
[#2518] feat(build): support Github CI for client-python

### PR DESCRIPTION
**Pull request by coolderli**
### What changes were proposed in this pull request?

 - use Gradle to manage Python build.
 - add Github CI
 - `./gradlew clean clients:client-python:test`

### Why are the changes needed?

Fix: #2518 

### Does this PR introduce _any_ user-facing change?

- no

### How was this patch tested?

- `./gradlew clean clients:client-python:test`

### CODE REVIEW

**Comment by coolderli** [comment]
@shaofengshi Could you please help view this? Thanks.

**Comment by shaofengshi** [comment]
Cool, this PR not only add the Github CI, but also use Gradle to run the python local test!

One quick question, if a user only has Java development environment ready, not setup python environment, will the Gradle build fail? Will it automatically install python and pip when run the test? @coolderli

**Comment by coolderli** [comment]
> Cool, this PR not only add the Github CI, but also use Gradle to run the python local test!
> 
> One quick question, if a user only has Java development environment ready, not setup python environment, will the Gradle build fail? Will it automatically install python and pip when run the test? @coolderli

@shaofengshi It will install Pip but not Python. If the user has no Python environment, the build will fail. I don't think we need to install the Python for users. Users may not want to install it automatically. I take a look at the `web` module. I think it has the same issue if there is a lake of `node.js`  in env. What do you think?

**Comment by shaofengshi** [comment]
> > Cool, this PR not only add the Github CI, but also use Gradle to run the python local test!
> > One quick question, if a user only has Java development environment ready, not setup python environment, will the Gradle build fail? Will it automatically install python and pip when run the test? @coolderli
> 
> @shaofengshi It will install Pip but not Python. If the user has no Python environment, the build will fail. I don't think we need to install the Python for users. Users may not want to install it automatically. I take a look at the `web` module. I think it has the same issue if there is a lake of `node.js` in env. What do you think?

I'm just curious about that; It make sense, I agree with you. Thank you Peidian!

@jerryshao @qqqttt123 please review and merge the PR if no objection to this.

**Review by jerryshao — APPROVED** [review]

**Comment by jerryshao** [comment]
Thanks @coolderli for your work, merging to main.

**Pull request merged**
