### PR TITLE
[MINOR] docs: Update MAINTAINERS.md

### PR DESCRIPTION
**Pull request by YxAc**
### What changes were proposed in this pull request?
- Add Xing Yong to Contributors list

### Why are the changes needed?
To: #3361

### CODE REVIEW

**Comment by YxAc** [comment]
cc @justinmclean @jerryshao

**Review by justinmclean — APPROVED** [review]
Thanks for adding your name

**Review by justinmclean — CHANGES_REQUESTED** [review]
We need each person to add thier own name.

**Comment by YxAc** [comment]
> We need each person to add their own name. This is similar to an ICLA so we need each person to agree that their contributions are under to Apache license.

I see, thx.

**Review by justinmclean — DISMISSED** [review]
Thanks for fixing that.

**Review by yuqi1129 — APPROVED** [review]

**Pull request merged**
