### PR TITLE
[#3771] improvement(client-python): Fix no-name-in-module and inconsistent-return-statements Pylint rule for client-python

### PR DESCRIPTION
**Pull request by noidname01**
### What changes were proposed in this pull request?

* Fix no-name-in-module and inconsistent-return-statements Pylint rule

### Why are the changes needed?

Fix: #3771 

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

`./gradlew clients:client-python:test`

### CODE REVIEW

**Review by jerryshao — APPROVED** [review]
LGMT, thanks @noidname01 for your contribution.

**Comment by jerryshao** [comment]
BTW, can you please fix the conflict?

**Comment by noidname01** [comment]
> BTW, can you please fix the conflict?

Sure, just done!

**Review by jerryshao — APPROVED** [review]
LGTM.

**Pull request merged**
