### PR TITLE
[#1624] improve(web): modified the usage document of web

### PR DESCRIPTION
**Pull request by ch3yne**
### What changes were proposed in this pull request?

Modified the usage document of web.

### Why are the changes needed?

Fix: #1624
Fix: #1623

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by justinmclean** [comment]
This is incomplete, how does a user run the Gravitino Web UI locally of port 3000?

**Comment by ch3yne** [comment]
> This is incomplete, how does a user run the Gravitino Web UI locally of port 3000?

This only applies to the development environment.

**Comment by justinmclean** [comment]
I'm sorry but I don't understand what you are trying to say, from what I can see these changes are not enough to make it clear to a user how they can start the Gravitino Web UI.

**Comment by ch3yne** [comment]
> I'm sorry but I don't understand what you are trying to say, from what I can see these changes are not enough to make it clear to a user how they can start the Gravitino Web UI.

If you're just using the web UI to manage the gravitino service, you only need to open port 8090, you don't need to start the web development service.

**Comment by ch3yne** [comment]
@justinmclean I modified the description of web.

**Review by justinmclean — APPROVED** [review]
LGTM

**Pull request merged**
