### PR TITLE
[#1958] improvement(common): replace stream.peek with map

### PR DESCRIPTION
**Pull request by YxAc**
### What changes were proposed in this pull request?
replace stream.peek with map

### Why are the changes needed?
Fix: #1958 

### Does this PR introduce _any_ user-facing change?
N/A

### How was this patch tested?
By hand

### CODE REVIEW

**Comment by yuqi1129** [comment]
@YxAc 
Please correct the format error.

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Comment by qqqttt123** [comment]
@yuqi1129 Should we back port this pull request to branch 0.4?

**Comment by yuqi1129** [comment]
> @yuqi1129 Should we back port this pull request to branch 0.4?

I don't think we need to backport it. What's your opinion?

**Comment by qqqttt123** [comment]
> > @yuqi1129 Should we back port this pull request to branch 0.4?
> 
> I don't think we need to backport it. What's your opinion?

We should back port this pull request if this is a bug. I'm confused about whether this is a bug.

**Comment by yuqi1129** [comment]
> about

I believe it's an improvement.

**Comment by justinmclean** [comment]
I would say it's a bug as "This can lead to peek() being unexpectedly called only for some or none of the elements in the Stream. As a consequence, relying on peek() can lead to error-prone code."

**Comment by jerryshao** [comment]
@YxAc Thanks a lot for your contribution.

**Pull request merged**
