### PR TITLE
[#3558] fix(client-python): specified tests packages version

### PR DESCRIPTION
**Pull request by featherchen**
### What changes were proposed in this pull request?

As title, specify pylint version in order to avoid unexpected bugs in the future development.

### Why are the changes needed?

Fix: #3558

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

`./gradlew build -x test` or `./gradlew :clients:client-python:pylint` for for the convenience.

### CODE REVIEW

**Comment by featherchen** [comment]
@noidname01 maybe you could help me check with this?

**Comment by noidname01** [comment]
@featherchen Thank you for mentioning this. The `pylint2` has different config file parser than `pylint3`, so it's important that we stick to specific version. Maybe you can help to lock other modules version?

**Comment by featherchen** [comment]
> @featherchen Thank you for mentioning this. The `pylint2` has different config file parser with `pylint3`, so it's important that we stick to specific version. Maybe you can help to lock other modules version?

@noidname01 Sure, I've specified the version based on the [CI](https://github.com/datastrato/gravitino/actions/runs/9218957516/job/25363368599#step:4:1175) in #3545, and I have also tested them on local machine. The process of gradle build should works properly now.

**Comment by noidname01** [comment]
@featherchen LGTM, Thanks

**Review by noidname01 — APPROVED** [review]

**Comment by jerryshao** [comment]
LGTM.

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
