### PR TITLE
[MINOR] test: Add missing docker it tag

### PR DESCRIPTION
**Pull request by jerryshao**
### What changes were proposed in this pull request?

Add missing docker it tag to the tests, so that test can run without Docker environment.

### Why are the changes needed?

Add missing docker-it tag to the tests, with this tag Gravitino can build without Docker environment.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Review by mchades — COMMENTED** [review]
Missing check classes in Spark module such as `com.datastrato.gravitino.spark.connector.integration.test.iceberg.SparkIcebergCatalogHiveBackendIT33`?

**Comment by yuqi1129** [comment]
> also missing `com.datastrato.gravitino.spark.connector.integration.test.iceberg.SparkIcebergCatalogIT`?

`SparkIcebergCatalogIT` is an abstract class and the `tag` annotation is not required.

**Comment by mchades** [comment]
> > also missing `com.datastrato.gravitino.spark.connector.integration.test.iceberg.SparkIcebergCatalogIT`?
> 
> `SparkIcebergCatalogIT` is an abstract class and the `tag` annotation is not required.

But it does have tests in it:
https://github.com/datastrato/gravitino/blob/2c9752898b474ab7b02718c4a7f2f5eaa186bb45/spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogIT.java#L93-L94

**Comment by jerryshao** [comment]
> > > also missing `com.datastrato.gravitino.spark.connector.integration.test.iceberg.SparkIcebergCatalogIT`?
> > 
> > 
> > `SparkIcebergCatalogIT` is an abstract class and the `tag` annotation is not required.
> 
> But it does have tests in it:
> 
> https://github.com/datastrato/gravitino/blob/2c9752898b474ab7b02718c4a7f2f5eaa186bb45/spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogIT.java#L93-L94

They already added the tag to the child class, so it is not necessary to add to the parent class.

**Comment by mchades** [comment]
> Missing check classes in Spark module such as `com.datastrato.gravitino.spark.connector.integration.test.iceberg.SparkIcebergCatalogHiveBackendIT33`?

Have checked this?

**Comment by jerryshao** [comment]
> SparkIcebergCatalogHiveBackendIT33

I see it already adds to the parent abstract class `SparkIcebergCatalogHiveBackendIT`, so it will not run the test. I've tested locally with docker shutdown, with this PR the build/test can run successfully without Docker environment.

**Review by mchades — APPROVED** [review]
LGTM

**Pull request merged**
