### PR TITLE
[MINOR] merge branch-spark-connector-dev to main

### PR DESCRIPTION
**Pull request by FANNG1**
### What changes were proposed in this pull request? 
merge branch-spark-connector-dev to main

### Why are the changes needed?
continue  spark-connector development on main

### Does this PR introduce _any_ user-facing change? no
no

### How was this patch tested?
existing UTs

### CODE REVIEW

**Comment by FANNG1** [comment]
@jerryshao @qqqttt123 could we merge it now?

**Comment by qqqttt123** [comment]
What changes were proposed in this pull request? Just modified some dependencies?

**Comment by FANNG1** [comment]
> What changes were proposed in this pull request? Just modified some dependencies?

only include https://github.com/datastrato/gravitino/pull/1582

**Review by qqqttt123 — APPROVED** [review]
LGTM.

**Comment by qqqttt123** [comment]
Could you modify the title and description of pull request?

**Pull request closed without merging**
