### PR TITLE
[#1968] improvement(web): Optimize header parameter of VersioningFilter.java

### PR DESCRIPTION
**Pull request by YxAc**
### What changes were proposed in this pull request?
optimize header parameter of VersioningFilter.java，use ACCEPT_VERSION_HEADER instead

### Why are the changes needed?
Fix: #1968 

### How was this patch tested?
By hand.

### CODE REVIEW

**Review by qqqttt123 — APPROVED** [review]
LGTM. thanks @YxAc

**Comment by qqqttt123** [comment]
Could you correct the word `para` in the title and description?

**Comment by YxAc** [comment]
> Could you correct the word `para` in the title and description?

done, thanks.

**Comment by qqqttt123** [comment]
Merged to master! Welcome @YxAc to join the Gravitino community. Enjoy your trip!

**Pull request merged**
