### PR TITLE
[MINOR] Fix incorrect numbering in the document

### PR DESCRIPTION
**Pull request by xleoken**
### What changes were proposed in this pull request?

Fix incorrect numbering in the document.

### Why are the changes needed?

Fix incorrect numbering in the document.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

local.

### CODE REVIEW

**Comment by yuqi1129** [comment]
@xleoken 
Thanks for your contribution. Can you modify your PR description as it's just a template?

**Comment by xleoken** [comment]
> @xleoken Thanks for your contribution. Can you modify your PR description as it's just a template?

Updated.

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Comment by jerryshao** [comment]
@xleoken thanks for your contribution, merging to main.

**Pull request merged**
