### PR TITLE
Happy new year!

### PR DESCRIPTION
**Pull request by justinmclean**
### What changes were proposed in this pull request?

Update year in the NOTICE files. Other files should be updated as needed.

### Why are the changes needed?

It's a new year.

Fix: # N/A

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

Built locally.

### CODE REVIEW

**Comment by qqqttt123** [comment]
Do we need to modify other file headers?

**Comment by jerryshao** [comment]
Just fix them all as a complete PR, don't just only fix two files.

**Comment by justinmclean** [comment]
Only the NOTICE files need to be updated as they relate to the whole product.

**Comment by jerryshao** [comment]
> Only the NOTICE files need to be updated as they relate to the whole product. We don't need to update all existing file headers. We should probably update the file headers if we change the files' contents.

OK, I see.

**Review by jerryshao — APPROVED** [review]
Thanks @justinmclean for the fix.

**Pull request merged**
