### PR TITLE
[#2402] test(spark-connector): Add the integration tests for CTAS and ITAS

### PR DESCRIPTION
**Pull request by FANNG1**
### What changes were proposed in this pull request?
add integrate test for `create table as select xx` and `insert table select xx`

### Why are the changes needed?
Fix: #2402 

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
IT

### CODE REVIEW

**Comment by FANNG1** [comment]
@jerryshao @qqqttt123  add test to `CTAS` and `ITAS` please help to review

**Comment by jerryshao** [comment]
So where is your actual code here, it's all about IT.

**Comment by FANNG1** [comment]
> So where is your actual code here, it's all about IT.

Spark combines datasourcev2 interfaces (CreateTable and Write) to support CTAS and ITAS, no need to do another work in Gravitino spark-connector.

```scala
case class CreateTableAsSelectExec {

  override protected def run(): Seq[InternalRow] = {
    if (catalog.tableExists(ident)) {
      if (ifNotExists) {
        return Nil
      }

      throw QueryCompilationErrors.tableAlreadyExistsError(ident)
    }

    val columns = CatalogV2Util.structTypeToV2Columns(
      CharVarcharUtils.getRawSchema(query.schema, conf).asNullable)
    val table = catalog.createTable(ident, columns,
      partitioning.toArray, properties.asJava)
    writeToTable(catalog, table, writeOptions, ident)
  }
}

```

**Comment by jerryshao** [comment]
Does Spark's CTAS directly talk to HMS to create a new table, or it will talk to Gravitino to do so?

**Comment by FANNG1** [comment]
> Does Spark's CTAS directly talk to HMS to create a new table, or it will talk to Gravitino to do so?

Using `catalog.createTable` to talk to Gravitino

**Review by jerryshao — APPROVED** [review]
LGTM. Thanks @FANNG1 for your work.

**Pull request merged**
