### PR TITLE
[#3537] improvement(hadooop-catalog):  Add e2e user authentication tests for Hadoop catalog.

### PR DESCRIPTION
**Pull request by yuqi1129**
### What changes were proposed in this pull request?

Add e2e user authentication tests for the Hadoop catalog.

### Why are the changes needed?

Fix: #3537 

### Does this PR introduce _any_ user-facing change?

N/A.

### How was this patch tested?

Test locally.

### CODE REVIEW

**Comment by yuqi1129** [comment]
This PR depends on #3525 and #3352

**Comment by yuqi1129** [comment]
@qqqttt123 
Could you please help to review?

**Review by qqqttt123 — DISMISSED** [review]
LGTM.

**Comment by jerryshao** [comment]
@qqqttt123 please help to review.

**Review by jerqi — APPROVED** [review]

**Review by qqqttt123 — APPROVED** [review]

**Pull request merged**
