### PR TITLE
improvement(client-python): add Namespace and NameIdentifier interface

### PR DESCRIPTION
**Pull request by coolderli**
### What changes were proposed in this pull request?

- add `Namespace` and `NameIdentifier` interface to `client-python`

### Why are the changes needed?

- `client-python` needs `Namespace` and `NameIdentifier` to represent a resource such as `metalake`, `schema`, `table`.

### Does this PR introduce _any_ user-facing change?

- yes, add client-python api about `Namespace` and `NameIdentifier`

### How was this patch tested?

- `pytest` in local

### CODE REVIEW

**Comment by coolderli** [comment]
@shaofengshi @Lanznx @SophieTech88 Could you help me review this? Thanks.

**Comment by shaofengshi** [comment]
LGTM; @zhaoyongjie yongjie, could you please take a look? thanks!

**Comment by zhaoyongjie** [comment]
Hey @coolderli, 

Thanks for introducing the new features in the Py client. I guess the aim of this feature is to construct an abstraction data-access layer (or data transfer layer) upon resources, while the other PR also introduces the same [utils](https://github.com/datastrato/gravitino/blob/main/clients/client-python/gravitino_client/core/dto.py#L8).

IMO, objects in Python naturally support dot access. Imagining, there is a `Table class` and a `Column class`, the property `columns` should be easily added to the Table class so that the `table.columns` property can straightforwardly access all columns.

But I welcome discussion on this PR.

**Comment by coolderli** [comment]
> Hey @coolderli,
> 
> Thanks for introducing the new features in the Py client. I guess the aim of this feature is to construct an abstraction data-access layer (or data transfer layer) upon resources, while the other PR also introduces the same [utils](https://github.com/datastrato/gravitino/blob/main/clients/client-python/gravitino_client/core/dto.py#L8).
> 
> IMO, objects in Python naturally support dot access. Imagining, there is a `Table class` and a `Column class`, the property `columns` should be easily added to the `Table class` so that the `table.columns` property can straightforwardly access all columns.
> 
> But I welcome discussion on this PR.

@zhaoyongjie Thanks for your reply. I think you may misunderstand the `NameIdentitfier ` and `Namespace`.  It's not an abstraction data-access layer.  It can identify a resource such as a metalake, a catalog, a schema, or a table.  You can see the `client-java`  about the different of the DTO and `NameIdentifier`.
https://github.com/datastrato/gravitino/blob/main/clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoMetalake.java#L97

**Pull request closed without merging**
