### PR TITLE
[MINOR] docs: fix formatting

### PR DESCRIPTION
**Pull request by zhoukangcn**
### What changes were proposed in this pull request?

- fix formatting

### Why are the changes needed?

Improve the table cell formatting

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

Local test

### CODE REVIEW

**Comment by yuqi1129** [comment]
@zhoukangcn 
Can you also align the table? I notice that this pr still can't make the table work well.
image
image
 


image

**Comment by zhoukangcn** [comment]
@yuqi1129 done. Thank you for your correction.

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Review by qqqttt123 — APPROVED** [review]

**Comment by qqqttt123** [comment]
@zhoukangcn Welcome to join the Gravitino community! Enjoy your trip!

**Comment by qqqttt123** [comment]
@zhoukangcn Could you raise a pr for branch 0.4?

**Comment by zhoukangcn** [comment]
@qqqttt123  #2224 is for branch-0.4, please review

**Pull request merged**
