### PR TITLE
[#2653] Improvement(common): Make clear the semantics of configuration alternatives

### PR DESCRIPTION
**Pull request by YxAc**
### What changes were proposed in this pull request?

1. make clear the semantics of configuration `alternatives` for storing the deprecated config keys.
2. log warning for all deprecated config keys when loading configurations
3. log warning when users try to call `config.set` of deprecated keys, just ignore the warning of `config.get`

### Why are the changes needed?
Fix: #2653 

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
By hand.

### CODE REVIEW

**Comment by YxAc** [comment]
@jerryshao @qqqttt123  can you help to review this PR?  Thx.

**Review by jerryshao — APPROVED** [review]
LGTM, thanks @YxAc for your contribution.

**Comment by qqqttt123** [comment]
@YxAc Could you add a test case for this pull request?

**Comment by YxAc** [comment]
> @YxAc Could you add a test case for this pull request?

@qqqttt123 I have check and thought the existing UT is enough for this.
This PR mainly correct and supplement the log warning on deprecated configurations.

Do you have some specific suggestion? Thx.

**Comment by qqqttt123** [comment]
> > @YxAc Could you add a test case for this pull request?
> 
> @qqqttt123 I have check and thought the existing UT is enough for this. This PR mainly correct and supplement the log warning on deprecated configurations.
> 
> Do you have some specific suggestion? Thx.

We should verify the logic. If new config option is absent and legacy is set, the value is legacy config option.  . If new config option and legacy one are set, the value should be new config option,

**Comment by YxAc** [comment]
> We should verify the logic. If new config option is absent and legacy is set, the value is legacy config option. . If new config option and legacy one are set, the value should be new config option,

@qqqttt123  As the UT in `TestConfigEntry` before, the first scenario as follows:
image

the second scenario:
image

Actually, the original implementation have support processing deprecated config, just the logging warning was ambiguous and incomplete, this PR just make logging clear and complete.

**Comment by qqqttt123** [comment]
> > We should verify the logic. If new config option is absent and legacy is set, the value is legacy config option. . If new config option and legacy one are set, the value should be new config option,
> 
> @qqqttt123 As the UT in `TestConfigEntry` before, the first scenario as follows:
> 
> image
> the second scenario:
> 
> image
> Actually, the original implementation have support processing deprecated config, just the logging warning was ambiguous and incomplete, this PR just make logging clear and complete.

I got it.

**Pull request merged**
