### PR TITLE
[#1955] imporvement(core): Fix resource leak in RocksDBKvBackend.java

### LINKED ISSUE #1955: [Improvement] Possible resource leak in `RocksDBKvBackend.java`
### What would you like to be improved?

In the method scan an exception could mean that db is not closed, same in deleteRange. Local varaible options is not closed in initRocksDB.

### How should we improve?

Use try/catch/finally and close options?

### PR DESCRIPTION
**Pull request by coolderli**
### What changes were proposed in this pull request?

close #1955

### Why are the changes needed?

(Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.)

Fix: #1955 

### Does this PR introduce _any_ user-facing change?
- no

### How was this patch tested?

- unit

### CODE REVIEW

**Comment by yuqi1129** [comment]
Overall, I'm okay with the changes. @coolderli Can you update the PR description to make it more standardized?

**Review by justinmclean — APPROVED** [review]
LGTM - thanks for your contribution!

**Comment by coolderli** [comment]
> Overall, I'm okay with the changes. @coolderli Can you update the PR description to make it more standardized?

I have updated the PR description. Please take a look. Thanks.

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Pull request merged**
