### PR TITLE
[#3048] feat(web): Add web UI support for Doris catalog

### PR DESCRIPTION
**Pull request by zhoukangcn**
### What changes were proposed in this pull request?

Add web UI support for Doris catalog
image
image

### Why are the changes needed?

Fix: #3048

### Does this PR introduce _any_ user-facing change?

N/A
### How was this patch tested?

Mannul

### CODE REVIEW

**Comment by yuqi1129** [comment]
@LauraXia123 @ch3yne 
Could you please help in reviewing this PR?

**Comment by jerryshao** [comment]
Maybe we should also have a specific icon for Doris. Anyway, is this change enough for Creating a Doris catalog?

**Comment by zhoukangcn** [comment]
image

**Comment by jerryshao** [comment]
I see, thanks. @LauraXia123 @ch3yne can you please help to review.

**Comment by LauraXia123** [comment]
LGTM

**Comment by LauraXia123** [comment]
It's going to add a custom icon for Doris catalog with a new PR.

**Comment by jerryshao** [comment]
OK, I'm going to merge this PR. @LauraXia123 please create a following PR to improve it.

**Review by jerryshao — APPROVED** [review]
LGTM. Thanks @zhoukangcn for your contribution.

**Comment by LauraXia123** [comment]
follow issue: https://github.com/datastrato/gravitino/issues/3085

**Pull request merged**
