### PR TITLE
[#3081] improvement(core): Remove hack in BaseCatalog.java

### PR DESCRIPTION
**Pull request by noidname01**
### What changes were proposed in this pull request?

Modify the description of `CATALOG_OPERATION_IMPL`, avoid the use of "hack"

### Why are the changes needed?

Fix: #3081 

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?
  
No need to test

### CODE REVIEW

**Comment by jerryshao** [comment]
@noidname01 Thanks a lot for your contribution. I think the issue is misleading, this part of the code is required for the advanced some users, we just leave a back door for such users without documentation.

**Comment by noidname01** [comment]
@jerryshao Sure, so this issue is not necessary?

**Comment by jerryshao** [comment]
I think what you need to do is to improve the comment to avoid saying that this is a hacky way. I think why @justinmclean created this issue is that he uses some tools to do code scan, that tool may trigger a warning when finding this keyword.

**Comment by noidname01** [comment]
OK, Got it

**Review by jerryshao — APPROVED** [review]
LGTM. Thanks a lot for your contribution.

**Pull request merged**
