### PR TITLE
[#2411] Add Apache Ranger Docker CI image and integration test

### PR DESCRIPTION
**Pull request by xunliu**
### What changes were proposed in this pull request?

This future includes：

1. A Gravitino Ranger CI Docker image
2. Add Ranger integration test
3. `docker run -it -p 6080:6080 datastrato/gravitino-ci-ranger`

### Why are the changes needed?

Created an Apache Ranger Docker image myself, because Apache Ranger's official Docker image has 5 child docker images, It's very complex.

Fix: #2411 

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

1. Created [datastrato/gravitino-ci-ranger:0.1.0](https://hub.docker.com/r/datastrato/gravitino-ci-ranger/tags) Docker image and pushed hub.docker.com successed.
2. CI Passed

### CODE REVIEW

**Comment by qqqttt123** [comment]
Could you add a document for this this pr in the `docker-image-details.md`?

**Comment by xunliu** [comment]
> Could you add a document for this this pr in the `docker-image-details.md`?

I already added document `Gravitino CI Apache Ranger image` in it.

**Comment by qqqttt123** [comment]
Have you released a Docker image by using this pr?

**Comment by xunliu** [comment]
> Have you released a Docker image using this pr?

Yes, I success create Ranger Docker image use this PR, https://hub.docker.com/r/datastrato/gravitino-ci-ranger/tags

**Comment by xunliu** [comment]
@qqqttt123 Please help me review this PR, Thanks.

**Review by jerqi — APPROVED** [review]
LGTM.

**Review by qqqttt123 — APPROVED** [review]

**Pull request merged**
