### PR TITLE
[#1079] improvement(CI): Modify the pipeline check logic in regards to code changes

### PR DESCRIPTION
**Pull request by qqqttt123**
### What changes were proposed in this pull request?
Modify the pipeline check logic in regards to code changes

### Why are the changes needed?

Fix: #1079 

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Tested by own repo. https://github.com/qqqttt123/gravitino/pull/3

### CODE REVIEW

**Comment by qqqttt123** [comment]
> This PR adds a check for source code changes so that the CI can determine whether to trigger the pipeline or not. Am I right?
> 
> Besides, the title ' Add doc to the', the `doc` is quite confusing...

Not exactly. If sources change, we will run the build job. Otherwise, we will run the compile-check job.

**Comment by yuqi1129** [comment]
> Not exactly. If sources change, we will run the build job. Otherwise, we will run the compile-check job.

I'm not very clear about `Otherwise, we will run the compile-check job`, you means if the code has not changed, we will run compile-check job?

What's the difference between `build` and `compile` job?

**Comment by yuqi1129** [comment]
> What's your suggestion?

What about the title 'Modify the pipeline check logic in regards to code changes'?

**Comment by qqqttt123** [comment]
> > Not exactly. If sources change, we will run the build job. Otherwise, we will run the compile-check job.
> 
> I'm not very clear about `Otherwise, we will run the compile-check job`, you means if the code has not changed, we will run compile-check job?
> 
> What's the difference between `build` and `compile` job?

Build job will run the tests. Compile job only run the rat check, lint check and compile the code.

**Comment by qqqttt123** [comment]
> > What's your suggestion?
> 
> What about the title 'Modify the pipeline check logic in regards to code changes'?

ok.

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Pull request merged**
