### PR TITLE
[3286] Improvement(ui): row tooltip displays comment

### PR DESCRIPTION
**Pull request by jtao1**
### What changes were proposed in this pull request?

In this PR, I've changed the tool tip to show the metalake comment and catalog comment when hovering over the metalake and catalog in each row respectively.

### Why are the changes needed?

Before the PR when hovering over the metalake row, it would display the metalake name which is redundant. Additionally, when hovering over the catalog name it did not show any tooltip at all.

Fix: #3286 

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?
I tested this using this the web UI to see if it displays correctly when the mouse is hovered over.

### CODE REVIEW

**Comment by LauraXia123** [comment]
@jtao1 Can you show some snapshots after changes? And fix the issue by danhua's suggestion which issue#3286 commented

**Comment by jtao1** [comment]
I've updated the PR to include Danhua's suggestion. I included images below to show the changes I've made. 

When hover over the metalake name, it shows the metalake comment.
image

When hover over catalog, it shows the catalog comment.
image

When hover over the metalake name when clicking on details, the tool tip is no longer shown; this was Danhua's suggestion.
image

**Comment by LauraXia123** [comment]
@jtao1 Please fix the ci issue by 'pnpm format'

**Comment by jtao1** [comment]
I've ran `pnpm format` and updated the PR.

**Comment by LauraXia123** [comment]
The ci test is failed by the catalog link changed maybe. Please check it.

**Comment by LauraXia123** [comment]
LGTM

**Review by LauraXia123 — APPROVED** [review]

**Pull request merged**
