### PR TITLE
[#3330] feat(spark-connector): use old create table interface to support mult spark version

### PR DESCRIPTION
**Pull request by FANNG1**
### What changes were proposed in this pull request?
use old create table interface to support mult spark version

### Why are the changes needed?
the current interface was introduced in Spark 3.4
the old create table table interface had better Spark version compatibility.

Fix: #3330 

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
existing test.

### CODE REVIEW

**Comment by qqqttt123** [comment]
Although we supported legacy interfaces, we still use new interfaces to implement the deprecated interfaces.

**Comment by FANNG1** [comment]
> Although we supported legacy interfaces, we still use new interfaces to implement the deprecated interfaces.

Sorry, I couldn't get your point :(

**Comment by jerryshao** [comment]
One possible way is that we implement this method in different Spark version's module, not in common module to avoid this issue?

**Comment by FANNG1** [comment]
> One possible way is that we implement this method in different Spark version's module, not in common module to avoid this issue?

yes, but this introduces redundant code which is located in different spark version's module.  And there seems no bad effect to using the old interface.

**Comment by qqqttt123** [comment]
> > Although we supported legacy interfaces, we still use new interfaces to implement the deprecated interfaces.
> 
> Sorry, I couldn't get your point :(

We should have all of  these methods at same time as follows.
```
createTable(
      Identifier ident, StructType schema, Transform[] partitions, Map<String, String> properties);

```
```
  public Table createTable(
      Identifier ident, Column[] columns, Transform[] transforms, Map<String, String> properties)
```

**Comment by FANNG1** [comment]
the new interface and `Column` type  was introduced in Spark 3.4 which couldn't be reused in older versions.

**Comment by jerqi** [comment]
> the new interface and `Column` type was introduced in Spark 3.4 which couldn't be reused in older versions.



> the new interface and `Column` type was introduced in Spark 3.4 which couldn't be reused in older versions.

Maybe you needn't to reuse, but we should have the similar interface. Maybe you can use object as the type. WDYT?

**Comment by FANNG1** [comment]
let's delay this until after spark multi version design is finished. cc @jerryshao @qqqttt123

**Pull request closed without merging**
