### PR TITLE
[#1204] improvement(all):  Move catalog property keys to the common module

### PR DESCRIPTION
**Pull request by yuqi1129**
### What changes were proposed in this pull request?

Move catalog/schema/table property keys to the common module, so that the module `trino-connector` can use it directly. 

### Why are the changes needed?

We need to make all module use the same property key and value reference, making it's convenient to manage and extend.

Fix: #1204

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

Existing tests can conver this change.

### CODE REVIEW

**Comment by jerryshao** [comment]
I was thinking of a better property system that can be shared between Trino and Gravitino, not just simply move the property name from A to B.

**Comment by jerryshao** [comment]
Can you do a basic design before doing the code works?

**Comment by yuqi1129** [comment]
> Can you do a basic design before doing the code works?

Can you give me some advice on what types of property systems we need to implement between Trino connector and Gravitino,  I have no full knowledge about it.

**Comment by jerryshao** [comment]
I think at least we should have a property system to check the key, value, and the validity of value, how to map between Gravitino and Trino, also how to check if the property is missing, not just a name.

**Comment by yuqi1129** [comment]
> I think at least we should have a property system to check the key, value, and the validity of value, how to map between Gravitino and Trino, also how to check if the property is missing, not just a name.

The initial development of the new scheme is here: https://docs.google.com/document/d/1wC4P4d2UgPTwJOu0L-dibhVz_wevolw3iuqFFRh1cO8/edit#heading=h.f7i6hp1bn8px

The core problem here:  We need to move catalog-related properties meta to common/api module, which is NOT well-designed and violates the catalog isolation principle. 

Please take a moment to review it and we can discuss it later.

**Comment by jerryshao** [comment]
@yuqi1129 , I'm going to close this, you can submit a new PR when you have a new solution.

**Pull request closed without merging**
