### PR TITLE
[#768] improvement(CI): Setting the workflow dependencies

### PR DESCRIPTION
**Pull request by xunliu**
### What changes were proposed in this pull request?

When build workflow successed in the Github Action then to execute Integration Test workflow.

### Why are the changes needed?

Fix: #768 

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

CI

### CODE REVIEW

**Comment by jerryshao** [comment]
My guess is that "build" is not a actual action name, maybe the correct one is "build (8)" or "build (11)", something like this.

**Comment by yuqi1129** [comment]
Why does the Integration test not appear in the CI task list?

**Comment by jerryshao** [comment]
I think this can also be a good first issue.

**Comment by qqqttt123** [comment]
> I think this can also be a good first issue.

+1, I add this issue to good first issues.

**Comment by qqqttt123** [comment]
We don't need this pr, too.

**Pull request closed without merging**
