### PR TITLE
[#1535] improve(web): remove sweetalert2

### PR DESCRIPTION
**Pull request by ch3yne**
### What changes were proposed in this pull request?

remove sweetalert2

### Why are the changes needed?

Fix: #1535 

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by justinmclean** [comment]
The license file (in the licenses directory) also needs to be removed.

**Comment by ch3yne** [comment]
> The license file (in the licenses directory) also needs to be removed.

Removed.

**Comment by jerryshao** [comment]
@ch3yne will this affect the current UI after sweetalert2 is removed?

**Comment by ch3yne** [comment]
> @ch3yne will this affect the current UI after sweetalert2 is removed?

No.
The current web functionality does not involve using sweetalert2 as a message modal.

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
