### PR TITLE
[#2194] Improvement(clients): Add NPE check for HTTPClient

### PR DESCRIPTION
**Pull request by YxAc**
### What changes were proposed in this pull request?
- Add NPE check for HTTPClient

### Why are the changes needed?
Fix: #2194 

### Does this PR introduce _any_ user-facing change?
N/A

### How was this patch tested?
By hand

### CODE REVIEW

**Comment by justinmclean** [comment]
We use Spotless to format the code consistently, looks like something has gone wrong here and I'll look into it for you.

**Comment by justinmclean** [comment]
Not sure what the issue was but rerunning the build fixed it.

**Comment by YxAc** [comment]
> We use Spotless to format the code consistently, looks like something has gone wrong here and I'll look into it for you.

Thx.

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Comment by yuqi1129** [comment]
@jerryshao, do you need to cherry-pick it to release 0.4.0?

**Comment by jerryshao** [comment]
> @jerryshao, do we need to cherry-pick it to release 0.4.0?

I think so.

**Comment by yuqi1129** [comment]
> I think so.

Got it.

**Pull request merged**
