### PR TITLE
[#1427] Order of Gravitino nullability and type columns 

### PR DESCRIPTION
**Pull request by hiirrxnn**
What changes were proposed in this pull request?
Order of Gravitino nullability and type columns 

Why are the changes needed?
For better UI

Does this PR introduce any user-facing change?
Changes order of table columns

How was this patch tested?
N/A.

### CODE REVIEW

**Comment by hiirrxnn** [comment]
Please review and suggest changes if any !

**Comment by ch3yne** [comment]
Hi @hiirrxnn , thank you for your contribution.
I think you can copy another branch based on the latest `main` branch to make the corresponding changes, because I see that there are still quite a few commits behind the `main` branch on the branch.

Example:

```
git checkout main
git pull upstream main
git checkout -b fix-1427

# change your code and submit the PR
```

**Comment by hiirrxnn** [comment]
Accidentally merged two issues I'm working on , #1427 and #1417 . Should i delete this PR and start over as this has become overly complicated.

**Comment by hiirrxnn** [comment]
Please review!

**Comment by ch3yne** [comment]
> Please review!

My suggestion is to open a new PR, it seems like these tests are looks hard to pass.

**Pull request closed without merging**
