### PR TITLE
[#1220]  improvement: Remove Lombok annotation from API module

### PR DESCRIPTION
**Pull request by 724thomas**
### What changes were proposed in this pull request?

This pull request introduces the following key changes:
- **Removal of '@Getter' and '@EqualsAndHashCode' Annotations**
- **Addition of Getter Methods**
- **Implementation of 'equals' and 'hashCode' Methods**
- **Custom 'toString' Method Implementations**: The format adopted is "METHOD NAME " + variable.

Special Handling:
- **Temporary Renaming for Windows Compatibility**: Encountered an issue with the "aux" directory, which is a reserved name in Windows environment. This directory was temporarily renamed during development to circumvent this issue.

**Justification for 'toString' Method Format**
The chosen format for the 'toString' method, "METHOD NAME " + variable", is in line with the existing style observed in other classes within the project.

Feedback on the changes, particularly the 'toString' method's format and the temporary workaround for the "aux" directory, is welcomed to ensure alignment with the project's coding conventions. If there are any concerns or preferences for a different approach, please let me know for necessary adjustments.

### Why are the changes needed?

Fix: #1220

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by qqqttt123** [comment]
Could you add new comments for new method?

**Comment by 724thomas** [comment]
> Could you add new Java doc comments for new method? For Gravitino, if a method or a class is public, we would better add Java doc for them.

Added Java doc comments for all methods. Also, removed annotations in SchemaChange.java. I found out that I've missed these out.

**Comment by 724thomas** [comment]
Also, applied spotless code formatting

**Review by qqqttt123 — DISMISSED** [review]
LGTM, cc @mchades .

**Comment by jerryshao** [comment]
@724thomas Would you please update the `api/build.gradle.kts` file to lombok dependency? Thanks.

**Comment by mchades** [comment]
Overall, LGTM, but the comment above needs to be addressed.

**Comment by jerryshao** [comment]
> Special Handling:
>
> Temporary Renaming for Windows Compatibility: Encountered an issue with the "aux" directory, which is a reserved name > in Windows environment. This directory was temporarily renamed during development to circumvent this issue.

@724thomas We have fixed this issue, can you please retest it, thanks.

**Comment by 724thomas** [comment]
> > Special Handling:
> > Temporary Renaming for Windows Compatibility: Encountered an issue with the "aux" directory, which is a reserved name > in Windows environment. This directory was temporarily renamed during development to circumvent this issue.
> 
> @724thomas We have fixed this issue, can you please retest it, thanks.

@jerryshao
Thank you for the update. I have retested the fix for the "aux" directory issue on Windows, and I can confirm that it now functions correctly.

Regarding the request to "update the api/build.gradle.kts file for the Lombok dependency", I would appreciate some additional clarification. From my understanding, this could involve either upgrading the version of Lombok from 1.18.20 to 1.18.30 or changing the dependency configuration from "compileOnly" to "implementation". Could you please specify which of these actions is required? I want to ensure that I accurately understand and implement the necessary changes to our project’s Lombok configuration.

Your guidance on this matter would be highly valuable.

**Comment by qqqttt123** [comment]
> > > Special Handling:
> > > Temporary Renaming for Windows Compatibility: Encountered an issue with the "aux" directory, which is a reserved name > in Windows environment. This directory was temporarily renamed during development to circumvent this issue.
> > 
> > 
> > @724thomas We have fixed this issue, can you please retest it, thanks.
> 
> @jerryshao Thank you for the update. I have retested the fix for the "aux" directory issue on Windows, and I can confirm that it now functions correctly.
> 
> Regarding the request to "update the api/build.gradle.kts file for the Lombok dependency", I would appreciate some additional clarification. From my understanding, this could involve either upgrading the version of Lombok from 1.18.20 to 1.18.30 or changing the dependency configuration from "compileOnly" to "implementation". Could you please specify which of these actions is required? I want to ensure that I accurately understand and implement the necessary changes to project’s Lombok configuration.
> 
> Your guidance on this matter would be highly valuable.

Could you remove the lombok dependency?

**Comment by jerryshao** [comment]
Sorry for my confusion, just removing the lombok dependencies is enough.

**Comment by 724thomas** [comment]
Last commit removes the Lombok dependency from the project, as specified in the requirements. Ensured the project builds successfully and all tests pass after the removal.

**Review by mchades — APPROVED** [review]
LGTM

**Pull request merged**
