### PR TITLE
 [#1369] Add RAT support for 2024 copyright header

### PR DESCRIPTION
**Pull request by justinmclean**
### What changes were proposed in this pull request?

Add RAT support for 2024 copyright header.

### Why are the changes needed?

Otherwise, RAT check will fail.

Fix: #1369

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

Tested locally.

### CODE REVIEW

**Comment by jerryshao** [comment]
@justinmclean please create an issue for this PR.

**Comment by jerryshao** [comment]
Does RAT check only check modified files or newly added file for this commit? I assume the CI will be failed for this change, but seems not.

**Comment by jerryshao** [comment]
@mchades can you please check this?

**Comment by justinmclean** [comment]
> Does RAT check only check modified files or newly added file for this commit? I assume the CI will be failed for this change, but seems not.

It doesn't, and AFAIK, it doesn't support this feature.

**Comment by jerryshao** [comment]
The rat check seems will always pass as it accepts both 2023 and 2024 in the header. Is there a way to fail the test if the header is forgot to modify.

**Comment by jerryshao** [comment]
Can we please change to "2023~2024" and refresh all the headers?

**Comment by mchades** [comment]
> > Does RAT check only check modified files or newly added file for this commit? I assume the CI will be failed for this change, but seems not.
> 
> It doesn't, and AFAIK, it doesn't support this feature.

Implementing this feature requires leveraging Git capabilities and new shell scripts, which seems quite cumbersome.

My suggestion is:
1. Remove the check for `Copyright 2023`, replace it with `Copyright 2024`, and in this PR, modify all the file headers to `Copyright 2024`.
or
2. Remove the check for `Copyright 2023`, replace it with `From 2023 until now`, and in this PR, modify all the file headers to `From 2023 until now`.

**Comment by justinmclean** [comment]
1. We cannot change all years to 2024 as copyright is loosely the data of the first publication.
2. We cannot use `From 2023 until now` or anything similar as that is not recognized.

I would suggest leave modified files as 2023 and any new file to contain 2024.

**Comment by justinmclean** [comment]
> Can we please change to "2023~2024" and refresh all the headers? @justinmclean

I'm not a laywer but my understanding is not legally possible and may in fact invalidate copyright.

**Comment by jerryshao** [comment]
My concern here is that the changes here don't force the contributors to update the license header to 2024, and we will have to notify the contributors manually in all the PR, this really is not a good way to do it.

**Comment by mchades** [comment]
> 1. We cannot change all years to 2024 as copyright is loosely the date of the first publication.
> 2. We cannot use `From 2023 until now` or anything similar as that is not recognized.
> 
> I would suggest leaving modified files having the copyright 2023 header and any new files to have a new copyright 2024 header. RAT is unable to check that new files have this headers but that's OK, it can check that files have a header and that's the more important part.

It seems that writing a custom Rat task is the only way to perfectly resolve this issue.

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
