### PR TITLE
[#1881] Improvement: ConfigConstants.java updated as class and is not an interface

### PR DESCRIPTION
**Pull request by ajayl83**
### What changes were proposed in this pull request?

  - ConfigConstants updated as class and is not an interface

### Why are the changes needed?

  - Fix: #1881

### Does this PR introduce any user-facing change?

 - No

### How was this patch tested?

 - ./gradlew build

### CODE REVIEW

**Comment by yuqi1129** [comment]
Can you format your PR description? it appears that the markdown subtitle has been removed. The following is an example.
image

**Comment by justinmclean** [comment]
We use Spotless to make our code consistently formatted. Can you run `./gradlew :common:spotlessApply` to fix this.

**Comment by ajayl83** [comment]
> justinmclean

i did run it  ,but i believe @yuqi1129 comment was over PR description .

**Review by justinmclean — APPROVED** [review]
LGTM - Thanks for your PR and your work on this.

**Comment by jerryshao** [comment]
LGTM. thanks @ajayl83 for your work.

**Pull request merged**
