### PR TITLE
[#3936] ci(web): update sleep millis of web ci

### PR DESCRIPTION
**Pull request by LauraXia123**
### What changes were proposed in this pull request?
update sleep millis of web ci

### Why are the changes needed?
api data inconsistencies with test cast by the instability response

Fix: #3936

### Does this PR introduce _any_ user-facing change?
N/A

### How was this patch tested?
manual test

### CODE REVIEW

**Comment by yuqi1129** [comment]
@LauraXia123 
The root cause is that the FE tests are not very reliable and can't load data in a timely manner?

**Comment by LauraXia123** [comment]
@yuqi1129 The log info show the data still the last response, so I guess the root cause maybe the list schema which is instability response.

**Comment by yuqi1129** [comment]
> @yuqi1129 The log info show the data still the last response, so I guess the root cause maybe the list schema which is instability response.

As we can't guarantee that the problem can be solved with this PR 100%, and things could not be worse, I'm going to merge this PR if there are no further comments.

**Comment by jerryshao** [comment]
1. Please fix the PR description.
2. Continue trigger the UI test for at least 10 times before merge.

**Comment by LauraXia123** [comment]
image
CI test rerun over 10 times, 9 passed and 1 failed by unkown error

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
