### PR TITLE
[#2628] improvement(client): remove tableDTO in client

### PR DESCRIPTION
**Pull request by mchades**
### What changes were proposed in this pull request?

- remove TableDTO in the client
- convert TableDTO to Table in the client

### Why are the changes needed?

Fix: #2628 

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

existing tests

### CODE REVIEW

**Comment by mchades** [comment]
After the changes, developers only need to focus on the API module without concerning themselves with `xxxDTO`

**Comment by FANNG1** [comment]
LGTM

**Comment by diqiu50** [comment]
LGTM

**Comment by mchades** [comment]
@jerryshao Please help to review when you have time, thanks!

**Comment by jerryshao** [comment]
You guys can go ahead if you feel confident.

**Review by FANNG1 — APPROVED** [review]

**Pull request merged**
