### PR TITLE
[#3088] Improvement(jdbc-doris): Improve greedy regular expressions for DorisExceptionConverter

### PR DESCRIPTION
**Pull request by BSSsunny**
### What changes were proposed in this pull request?

https://github.com/datastrato/gravitino/issues/3088

### Why are the changes needed?
In DorisExceptionConverter.java we have a greedy regular expression that could potentially cause issues

### Does this PR introduce _any_ user-facing change?
No
### How was this patch tested?
 IT&UT

### CODE REVIEW

**Comment by jerryshao** [comment]
@yuqi1129 @zhoukangcn would you please help to review this?

**Comment by zhoukangcn** [comment]
LGTM

**Comment by yuqi1129** [comment]
@BSSsunny 
Could you update your PR description to align with that of other PRs?

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Comment by BSSsunny** [comment]
[Improvement]（catalogs） Improve greedy regular expressions 
Is it right ?I'm sorry,this is my first pr.

**Comment by zhoukangcn** [comment]
PR's Title should be : `[#3088]improvement(jdbc-doris): Improve greedy regular expressions for DorisExceptionConverter`

and Content should be

```
### What changes were proposed in this pull request?
Improve greedy regular expression in DorisExceptionConverter.java to xxxxx

### Why are the changes needed?
fix: #3088

Does this PR introduce any user-facing change?
N/A

How was this patch tested?
UT & IT
```

**Comment by BSSsunny** [comment]
Thanks for your help,I have changed it.

**Comment by yuqi1129** [comment]
> Thanks for your help,I have changed it.

Have you altered this aspect?
image

**Comment by BSSsunny** [comment]
> > 谢谢你的帮助，我已经改变了它。
> 
> 你改变了这方面吗？ image

I'm sorry.Maybe it didn't take effect when I modified it. I checked it again and modified it.

**Comment by yuqi1129** [comment]
> > > 谢谢你的帮助，我已经改变了它。
> > 
> > 
> > 你改变了这方面吗？ image
> 
> I'm sorry.Maybe it didn't take effect when I modified it. I checked it again and modified it.

Can you change `UT & IT` to the `Existing test can cover it` or you can add some tests to verify your changes?

**Comment by BSSsunny** [comment]
> > > > 谢谢你的帮助，我已经改变了它。
> > > 
> > > 
> > > 你改变了这方面吗？ image
> > 
> > 
> > I'm sorry.Maybe it didn't take effect when I modified it. I checked it again and modified it.
> 
> Can you change to the or you can add some tests to verify your changes?`UT & IT``Existing test can cover it`

Sorry maybe I should add tests for this change.

**Comment by jerryshao** [comment]
@BSSsunny can you please move forward this?

**Comment by BSSsunny** [comment]
> @BSSsunny can you please move forward this?

I'm sorry l've been so busy with exams and interviews that l don't have the energy to do it

**Comment by BSSsunny** [comment]
> 你能推进这个吗？

I'm sorry l've been so busy with exams and interviews that l don't have the energy to do it

**Pull request merged**
