### PR TITLE
feat(client-python): support Github CI for client-python

### PR DESCRIPTION
**Pull request by coolderli**
### What changes were proposed in this pull request?

- add github ci to test python

### Why are the changes needed?

- Fix: #2518 

### Does this PR introduce _any_ user-facing change?

- no

### How was this patch tested?

- github pipeline

### CODE REVIEW

**Comment by coolderli** [comment]
@shaofengshi Hi, I use Github ci to have a test. Does this meet our needs?

**Comment by jerryshao** [comment]
I think we'd better integrate with gradle, so one gradle command can run all the build/test things. The changes here only do the github CI, we still cannot run it locally.

**Comment by shaofengshi** [comment]
Peidian, will this change make the github action longer? If the PR doesn't have change on Python, will the test python be triggred also? @coolderli

**Comment by coolderli** [comment]
> Peidian, will this change make the github action longer? If the PR doesn't have change on Python, will the test python be triggred also? @coolderli

@shaofengshi Yes, this will always be triggered for now. We can add some restrictions to it.

**Comment by coolderli** [comment]
close this. because there is a new patch: https://github.com/datastrato/gravitino/pull/2684

**Pull request closed without merging**
