### PR TITLE
[#3944] fix(pyClient): Python client loss depends library in the requirements-dev

### PR DESCRIPTION
**Pull request by xunliu**
### What changes were proposed in this pull request?

Add lose Python depends on library into `requirements-dev.txt`
```
cachetools==5.3.3
readerwriterlock==1.0.9
```

### Why are the changes needed?

Fix: #3944

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

CI Passed.

### CODE REVIEW

**Comment by xunliu** [comment]
@coolderli @noidname01 Please help me review this PR, Thanks!

**Comment by noidname01** [comment]
LGTM

**Comment by coolderli** [comment]
LGTM!

**Comment by jerryshao** [comment]
@xloya can you please help to review. I asked the same question there, and you mentioned that it is not necessary as it already declared in another requirement file.

**Comment by xloya** [comment]
> @xloya can you please help to review. I asked the same question there, and you mentioned that it is not necessary as it already declared in another requirement file.
@jerryshao According to the original issue stack, it seems to be another problem. My initial guess is that the `pip install` command is not executed locally based on the latest client, so related dependencies such as `cachetools` are not installed locally. We only specify `cachetools` dependency in the `requirement.txt`, but not in the `requirement-dev.txt`. Therefore, if there is no `cachetools` dependency locally and the integration test is executed directly, this problem will occur.

I think we have two solutions:
1. We configure the same dependencies in `requirement.txt` and `requirement-dev.txt`.
2. In the gradle script, we can first execute the `pip install` command to install the latest dependencies locally before running unit tests or integration tests. WDYT?

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
