### PR TITLE
[#1967][#1964][#1917][#1960][#1959][#1956][#1952][#1951][#1943][#1939][#1936][#1934][#1925][#1927][#1915][#1897][#1892][#1890][#1886][#1885][#1869 ] Improvement: Missing private constructor

### PR DESCRIPTION
**Pull request by codeHysteria28**
### What changes were proposed in this pull request?

Utility classes were updated with private constructors.

### Why are the changes needed?

Utility classes contain only static members that we group together around a specific topic. Thus, the classes themselves are stateless, while their members contain code meant to be reused across several layers.

**Fix**

Fix: #1967
Fix: #1917
Fix: #1964
Fix: #1960
Fix: #1959
Fix: #1956
Fix: #1952
Fix: #1951
Fix: #1943
Fix: #1939
Fix: #1936
Fix: #1934
Fix: #1925
Fix: #1915
Fix: #1897
Fix: #1892
Fix: #1890
Fix: #1886
Fix: #1885
Fix: #1869

### CODE REVIEW

**Comment by codeHysteria28** [comment]
Resolves: #1967, #1964, #1960, #1959, #1956, #1952, #1951, #1943, #1939, #1936, #1934, #1925, #1927, #1915, #1897, #1892, #1890, #1886, #1885, #1869

**Comment by YxAc** [comment]
cool, maybe you can change the title 'feat' to 'improvement' ?

**Comment by codeHysteria28** [comment]
> cool, maybe you can change the title 'feat' to 'improvement' ?

Just changed...

Should I also run ./gradlew :common:spotlessApply ? I've seen this being referenced in another PR.

**Comment by justinmclean** [comment]
Thanks for your contribution. There is no need for the comment "// private constructor" as it doesn't add anything. Also, there's no need to throw an exception, as a private constructor can't usually be called from outside the class.

You should run ` ./gradlew build -x test`, and if there are any issues with the code formatting you may need to run spotlessApply.

**Comment by jerryshao** [comment]
Can you please change the PR tile to like "[#xxx][#xxx][#xxx]..." to follow our convention. Also please add the `Fix: #xxx` in the PR description one by one line, which will close the related issues when this PR is closed. You can follow what other PR did.

**Comment by yuqi1129** [comment]
@codeHysteria28 
Can you format your code (./gradlew :api:spotlessApply) to fix CI failure?

**Comment by codeHysteria28** [comment]
> @codeHysteria28 Can you format your code (./gradlew :api:spotlessApply) to fix CI failure?

yes will do !

**Comment by codeHysteria28** [comment]
Tests all build successfully and also formatting should be fixed. Pushing the changes to this PR.

**Comment by yuqi1129** [comment]
LGTM

**Review by yuqi1129 — APPROVED** [review]

**Comment by yuqi1129** [comment]
Thanks @codeHysteria28 for your contributions.

**Pull request merged**
