### PR TITLE
[#1299] Fix the copyright year

### PR DESCRIPTION
**Pull request by justinmclean**
### What changes were proposed in this pull request?

Fix the copyright year to be the year of the last release, not the current year.

### Why are the changes needed?

The copyright year should not automatically update to the current year.

Fix: #1299

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

Built and tested locally in a browser.

### CODE REVIEW

**Comment by jerryshao** [comment]
@ch3yne can you please help to review?

**Comment by ch3yne** [comment]
LGTM

**Review by ch3yne — APPROVED** [review]
LGTM

**Comment by qqqttt123** [comment]
Does this pull request need to back port branch 0.3?

**Comment by jerryshao** [comment]
> Does this pull request need to back port branch 0.3?

Yeah, it is needed.

**Pull request merged**
