### PR TITLE
[#2340] improve: MySQL int unsigned type mapping to gravitino Long type

### PR DESCRIPTION
**Pull request by hanwxx**
### What changes were proposed in this pull request?
Convert MySQL int unsigned type => gravitino Long type

### Why are the changes needed?
Refer [MySQL Type conversions](https://dev.mysql.com/doc/connector-j/en/connector-j-reference-type-conversions.html)

fix: #2340

### Does this PR introduce _any_ user-facing change?
 No

### How was this patch tested?
1. UT
2. UI TEST

### CODE REVIEW

**Comment by yuqi1129** [comment]
I'm afraid converting `unsigned int` to `long` will cause type conversion issues in some cases though we did need type `long` to hold `unsigned int` data.

**Comment by SteNicholas** [comment]
@hanwxx, @yuqi1129, IMO, all unsigned data type should be converted, not only `INT UNSIGNED`.

**Comment by yuqi1129** [comment]
> @hanwxx, @yuqi1129, IMO, all unsigned data type should be converted, not only `INT UNSIGNED`.

I agree, but things seem to be not as simple as they seem.

> @hanwxx, @yuqi1129, IMO, all unsigned data type should be converted, not only `INT UNSIGNED`.

Total agree. Things are not as simple as they seem.

**Comment by coolderli** [comment]
@yuqi1129 @SteNicholas Any advice about how to handle these `unsigned` types? It may be a common case. 
@hanwxx Can you share some experience about metacat?

**Comment by yuqi1129** [comment]
> > @hanwxx, @yuqi1129, IMO, all unsigned data type should be converted, not only `INT UNSIGNED`.
> 
> I agree, but things seem to be not as simple as they seem.

I think we should consider the following points:
- How to create an `unsigned` column through Gravitino and the corresponding type mapping between catalogs and Gravitino. 
- Data range overflow issue, how do we map types like `unsigned bigint` as Java primitive type `long` can't hold it.

**Comment by hanwxx** [comment]
> > > @hanwxx, @yuqi1129, IMO, all unsigned data type should be converted, not only `INT UNSIGNED`.
> > 
> > 
> > I agree, but things seem to be not as simple as they seem.
> 
> I think we should consider the following points:
> 
> * How to create an `unsigned` column through Gravitino and the corresponding type mapping between catalogs and Gravitino.
> * Data range overflow issue, how do we map types like `unsigned bigint` as Java primitive type `long` can't hold it.
Mapping unsigned types to wider type can solve 2，but can not support 1
tinyint unsigned -> smallint
smallint unsigned -> integer
integer unsigned -> bigint
bigint unsigned -> decimal(20,0)

**Comment by hanwxx** [comment]
> * ta range overflow issue, how do we map types like `unsigned bigint` as Java primitive type `long` can't hold it.


> @yuqi1129 @SteNicholas Any advice about how to handle these `unsigned` types? It may be a common case. @hanwxx Can you share some experience about metacat?
like this : 
"source_type": "INT(10) UNSIGNED",
 "type": "int",

**Comment by mchades** [comment]
@hanwxx Have you made any progress on this?  I suggest adding a boolean parameter, `signed`, to the `IntegralType`

**Comment by mchades** [comment]
duplicated with #3505

**Pull request closed without merging**
