### PR TITLE
[#1755] fix(core): update guava from 31.1-jre to 32.1.3-jre

### PR DESCRIPTION
**Pull request by FANNG1**
### What changes were proposed in this pull request?
update guava from 31.1-jre to 32.1.3-jre

### Why are the changes needed?

Fix: #1755 

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
existing tests

### CODE REVIEW

**Comment by jerryshao** [comment]
Seems there're some issue in upgrading?

**Comment by FANNG1** [comment]
There're some test failures in trino, @diqiu50 could you help to check it?

```java
testAlterTable() {
    assertQueryFails(
        String.format("alter table %s add column if not exists c varchar", fullTableName1),
        format("This connector does not support adding columns"));
}
```

**Comment by FANNG1** [comment]
with the help of @yuqi1129 , upgrade mockito to fix trino ut failure.

**Comment by FANNG1** [comment]
test failure seems not related, run again.
```
MetalakePageTest > initializationError FAILED
    java.lang.RuntimeException: Webpage not loaded in 60 seconds.
        at com.datastrato.gravitino.integration.test.web.ui.utils.WebDriverManager.getWebDriver(WebDriverManager.java:53)
        at com.datastrato.gravitino.integration.test.web.ui.utils.AbstractWebIT.startUp(AbstractWebIT.java:22)
```

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
